name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies and build
        run: |
          deno cache scripts/*.ts tests/*.ts
          deno task build
      - name: Type check
        run: deno check ./**/*.ts
      - name: Format
        run: deno task fmt:check
      - name: Lint
        run: deno task lint
      - name: Test
        run: deno test -A
      - name: Package Extension
        id: packageExtension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          dryRun: true
